# Generated by Django 4.1.7 on 2023-03-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='countryname',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fcityname',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='statename',
            new_name='state',
        ),
    ]
